//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoadCare3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ImagePath")]
        public string IMAGE_PATH {
            get {
                return ((string)(this["IMAGE_PATH"]));
            }
            set {
                this["IMAGE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LOCAL_PATH {
            get {
                return ((string)(this["LOCAL_PATH"]));
            }
            set {
                this["LOCAL_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ASSETS_COLORS {
            get {
                return ((string)(this["ASSETS_COLORS"]));
            }
            set {
                this["ASSETS_COLORS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DATABASE_DIU {
            get {
                return ((string)(this["DATABASE_DIU"]));
            }
            set {
                this["DATABASE_DIU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PROVIDER_DIU {
            get {
                return ((string)(this["PROVIDER_DIU"]));
            }
            set {
                this["PROVIDER_DIU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string USERNAME_DIU {
            get {
                return ((string)(this["USERNAME_DIU"]));
            }
            set {
                this["USERNAME_DIU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SERVER_DIU {
            get {
                return ((string)(this["SERVER_DIU"]));
            }
            set {
                this["SERVER_DIU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ATTRIBUTE_DEFAULT {
            get {
                return ((int)(this["ATTRIBUTE_DEFAULT"]));
            }
            set {
                this["ATTRIBUTE_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSSQL")]
        public string PROVIDER_DEFAULT {
            get {
                return ((string)(this["PROVIDER_DEFAULT"]));
            }
            set {
                this["PROVIDER_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NUMBER")]
        public string TYPE_DEFAULT {
            get {
                return ((string)(this["TYPE_DEFAULT"]));
            }
            set {
                this["TYPE_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int MAXIMUM_DEFAULT {
            get {
                return ((int)(this["MAXIMUM_DEFAULT"]));
            }
            set {
                this["MAXIMUM_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int MINIMUM_DEFAULT {
            get {
                return ((int)(this["MINIMUM_DEFAULT"]));
            }
            set {
                this["MINIMUM_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEVEL1_DEFAULT {
            get {
                return ((string)(this["LEVEL1_DEFAULT"]));
            }
            set {
                this["LEVEL1_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEVEL2_DEFAULT {
            get {
                return ((string)(this["LEVEL2_DEFAULT"]));
            }
            set {
                this["LEVEL2_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEVEL3_DEFAULT {
            get {
                return ((string)(this["LEVEL3_DEFAULT"]));
            }
            set {
                this["LEVEL3_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEVEL4_DEFAULT {
            get {
                return ((string)(this["LEVEL4_DEFAULT"]));
            }
            set {
                this["LEVEL4_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LEVEL5_DEFAULT {
            get {
                return ((string)(this["LEVEL5_DEFAULT"]));
            }
            set {
                this["LEVEL5_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DEFAULT_VALUE {
            get {
                return ((string)(this["DEFAULT_VALUE"]));
            }
            set {
                this["DEFAULT_VALUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LIGHTON.ICO")]
        public string ACTIVE_IMAGE_KEY {
            get {
                return ((string)(this["ACTIVE_IMAGE_KEY"]));
            }
            set {
                this["ACTIVE_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LIGHTON.ICO")]
        public string ACTIVE_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["ACTIVE_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["ACTIVE_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roadnetwork.ico")]
        public string NETWORK_IMAGE_KEY {
            get {
                return ((string)(this["NETWORK_IMAGE_KEY"]));
            }
            set {
                this["NETWORK_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roadnetwork.ico")]
        public string NETWORK_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["NETWORK_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["NETWORK_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("db.ico")]
        public string ATTRIBUTE_IMAGE_KEY {
            get {
                return ((string)(this["ATTRIBUTE_IMAGE_KEY"]));
            }
            set {
                this["ATTRIBUTE_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("db.ico")]
        public string ATTRIBUTE_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["ATTRIBUTE_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["ATTRIBUTE_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roadnetwork.ico")]
        public string SEGMENTATION_IMAGE_KEY {
            get {
                return ((string)(this["SEGMENTATION_IMAGE_KEY"]));
            }
            set {
                this["SEGMENTATION_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roadnetwork.ico")]
        public string SEGMENTATION_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["SEGMENTATION_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["SEGMENTATION_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roadnetwork.ico")]
        public string SEGMENTATION_LOGIC_IMAGE_KEY {
            get {
                return ((string)(this["SEGMENTATION_LOGIC_IMAGE_KEY"]));
            }
            set {
                this["SEGMENTATION_LOGIC_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roadnetwork.ico")]
        public string SEGMENTATION_LOGIC_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["SEGMENTATION_LOGIC_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["SEGMENTATION_LOGIC_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roadnetwork.ico")]
        public string SEGMENTATION_RESULTS_IMAGE_KEY {
            get {
                return ((string)(this["SEGMENTATION_RESULTS_IMAGE_KEY"]));
            }
            set {
                this["SEGMENTATION_RESULTS_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roadnetwork.ico")]
        public string SEGMENTATION_RESULTS_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["SEGMENTATION_RESULTS_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["SEGMENTATION_RESULTS_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roadnetwork.ico")]
        public string ROLLUP_IMAGE_KEY {
            get {
                return ((string)(this["ROLLUP_IMAGE_KEY"]));
            }
            set {
                this["ROLLUP_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roadnetwork.ico")]
        public string ROLLUP_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["ROLLUP_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["ROLLUP_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("construction.ico")]
        public string CONSTRUCTION_HISTORY_IMAGE_KEY {
            get {
                return ((string)(this["CONSTRUCTION_HISTORY_IMAGE_KEY"]));
            }
            set {
                this["CONSTRUCTION_HISTORY_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("construction.ico")]
        public string CONSTRUCTION_HISTORY_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["CONSTRUCTION_HISTORY_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["CONSTRUCTION_HISTORY_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bluedb.ico")]
        public string ASSET_IMAGE_KEY {
            get {
                return ((string)(this["ASSET_IMAGE_KEY"]));
            }
            set {
                this["ASSET_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bluedb.ico")]
        public string ASSET_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["ASSET_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["ASSET_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("construction.ico")]
        public string CONSTRUCTION_HISTORY_VIEW_IMAGE_KEY {
            get {
                return ((string)(this["CONSTRUCTION_HISTORY_VIEW_IMAGE_KEY"]));
            }
            set {
                this["CONSTRUCTION_HISTORY_VIEW_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("construction.ico")]
        public string CONSTRUCTION_HISTORY_VIEW_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["CONSTRUCTION_HISTORY_VIEW_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["CONSTRUCTION_HISTORY_VIEW_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("orange.ico")]
        public string SECTION_VIEW_IMAGE_KEY {
            get {
                return ((string)(this["SECTION_VIEW_IMAGE_KEY"]));
            }
            set {
                this["SECTION_VIEW_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("orange.ico")]
        public string SECTION_VIEW_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["SECTION_VIEW_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["SECTION_VIEW_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("blue.ico")]
        public string ASSET_VIEW_IMAGE_KEY {
            get {
                return ((string)(this["ASSET_VIEW_IMAGE_KEY"]));
            }
            set {
                this["ASSET_VIEW_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("blue.ico")]
        public string ASSET_VIEW_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["ASSET_VIEW_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["ASSET_VIEW_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("map.ico")]
        public string GIS_VIEW_IMAGE_KEY {
            get {
                return ((string)(this["GIS_VIEW_IMAGE_KEY"]));
            }
            set {
                this["GIS_VIEW_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("map.ico")]
        public string GIS_VIEW_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["GIS_VIEW_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["GIS_VIEW_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pink.ico")]
        public string SIMULATION_IMAGE_KEY {
            get {
                return ((string)(this["SIMULATION_IMAGE_KEY"]));
            }
            set {
                this["SIMULATION_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pink.ico")]
        public string SIMULATION_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["SIMULATION_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["SIMULATION_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("class.ico")]
        public string ATTRIBUTE_VIEW_IMAGE_KEY {
            get {
                return ((string)(this["ATTRIBUTE_VIEW_IMAGE_KEY"]));
            }
            set {
                this["ATTRIBUTE_VIEW_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("class.ico")]
        public string ATTRIBUTE_VIEW_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["ATTRIBUTE_VIEW_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["ATTRIBUTE_VIEW_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("orange.ico")]
        public string ATTRIBUTE_VIEW_SPECIFIC_YEAR_IMAGE_KEY {
            get {
                return ((string)(this["ATTRIBUTE_VIEW_SPECIFIC_YEAR_IMAGE_KEY"]));
            }
            set {
                this["ATTRIBUTE_VIEW_SPECIFIC_YEAR_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("orange.ico")]
        public string ATTRIBUTE_VIEW_SPECIFIC_YEAR_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["ATTRIBUTE_VIEW_SPECIFIC_YEAR_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["ATTRIBUTE_VIEW_SPECIFIC_YEAR_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("orange.ico")]
        public string SIMULATION_ATTRIBUTE_YEAR_IMAGE_KEY {
            get {
                return ((string)(this["SIMULATION_ATTRIBUTE_YEAR_IMAGE_KEY"]));
            }
            set {
                this["SIMULATION_ATTRIBUTE_YEAR_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("orange.ico")]
        public string SIMULATION_ATTRIBUTE_YEAR_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["SIMULATION_ATTRIBUTE_YEAR_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["SIMULATION_ATTRIBUTE_YEAR_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roadnetwork.ico")]
        public string LINEAR_NETWORK_DEFINITION_IMAGE_KEY {
            get {
                return ((string)(this["LINEAR_NETWORK_DEFINITION_IMAGE_KEY"]));
            }
            set {
                this["LINEAR_NETWORK_DEFINITION_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roadnetwork.ico")]
        public string LINEAR_NETWORK_DEFINITION_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["LINEAR_NETWORK_DEFINITION_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["LINEAR_NETWORK_DEFINITION_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roadnetwork.ico")]
        public string SECTION_NETWORK_DEFINITION_IMAGE_KEY {
            get {
                return ((string)(this["SECTION_NETWORK_DEFINITION_IMAGE_KEY"]));
            }
            set {
                this["SECTION_NETWORK_DEFINITION_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("roadnetwork.ico")]
        public string SECTION_NETWORK_DEFINITION_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["SECTION_NETWORK_DEFINITION_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["SECTION_NETWORK_DEFINITION_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ROADCARE_FILE_PATH {
            get {
                return ((string)(this["ROADCARE_FILE_PATH"]));
            }
            set {
                this["ROADCARE_FILE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DBDATABASE {
            get {
                return ((string)(this["DBDATABASE"]));
            }
            set {
                this["DBDATABASE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DBSERVER {
            get {
                return ((string)(this["DBSERVER"]));
            }
            set {
                this["DBSERVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DBPORT {
            get {
                return ((string)(this["DBPORT"]));
            }
            set {
                this["DBPORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DBSID {
            get {
                return ((string)(this["DBSID"]));
            }
            set {
                this["DBSID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DBNETWORKALIAS {
            get {
                return ((string)(this["DBNETWORKALIAS"]));
            }
            set {
                this["DBNETWORKALIAS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultTab {
            get {
                return ((string)(this["DefaultTab"]));
            }
            set {
                this["DefaultTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSSQL")]
        public string LAST_DB_TYPE {
            get {
                return ((string)(this["LAST_DB_TYPE"]));
            }
            set {
                this["LAST_DB_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_DB_SERVER {
            get {
                return ((string)(this["LAST_DB_SERVER"]));
            }
            set {
                this["LAST_DB_SERVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_DB {
            get {
                return ((string)(this["LAST_DB"]));
            }
            set {
                this["LAST_DB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_GROUP {
            get {
                return ((string)(this["LAST_GROUP"]));
            }
            set {
                this["LAST_GROUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_ONE {
            get {
                return ((string)(this["LAST_ONE"]));
            }
            set {
                this["LAST_ONE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_TWO {
            get {
                return ((string)(this["LAST_TWO"]));
            }
            set {
                this["LAST_TWO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_THREE {
            get {
                return ((string)(this["LAST_THREE"]));
            }
            set {
                this["LAST_THREE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_FOUR {
            get {
                return ((string)(this["LAST_FOUR"]));
            }
            set {
                this["LAST_FOUR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_FIVE {
            get {
                return ((string)(this["LAST_FIVE"]));
            }
            set {
                this["LAST_FIVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_DEFAULT {
            get {
                return ((string)(this["LAST_DEFAULT"]));
            }
            set {
                this["LAST_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_FORMAT {
            get {
                return ((string)(this["LAST_FORMAT"]));
            }
            set {
                this["LAST_FORMAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_MINIMUM {
            get {
                return ((string)(this["LAST_MINIMUM"]));
            }
            set {
                this["LAST_MINIMUM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_MAXIMUM {
            get {
                return ((string)(this["LAST_MAXIMUM"]));
            }
            set {
                this["LAST_MAXIMUM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_PASSWORD {
            get {
                return ((string)(this["LAST_PASSWORD"]));
            }
            set {
                this["LAST_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LAST_LOGIN {
            get {
                return ((string)(this["LAST_LOGIN"]));
            }
            set {
                this["LAST_LOGIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool USE_INTEGRATED_SECURITY {
            get {
                return ((bool)(this["USE_INTEGRATED_SECURITY"]));
            }
            set {
                this["USE_INTEGRATED_SECURITY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CONNECTION_TYPE {
            get {
                return ((string)(this["CONNECTION_TYPE"]));
            }
            set {
                this["CONNECTION_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ORACLE_USE_SID {
            get {
                return ((bool)(this["ORACLE_USE_SID"]));
            }
            set {
                this["ORACLE_USE_SID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ORACLE_DB_USERNAME {
            get {
                return ((string)(this["ORACLE_DB_USERNAME"]));
            }
            set {
                this["ORACLE_DB_USERNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ORACLE_DB_PASSWORD {
            get {
                return ((string)(this["ORACLE_DB_PASSWORD"]));
            }
            set {
                this["ORACLE_DB_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NETWORK_DEFINITION_NAME {
            get {
                return ((string)(this["NETWORK_DEFINITION_NAME"]));
            }
            set {
                this["NETWORK_DEFINITION_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NNDServer {
            get {
                return ((string)(this["NNDServer"]));
            }
            set {
                this["NNDServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NNDDatabase {
            get {
                return ((string)(this["NNDDatabase"]));
            }
            set {
                this["NNDDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NNDUserName {
            get {
                return ((string)(this["NNDUserName"]));
            }
            set {
                this["NNDUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NNDPassword {
            get {
                return ((string)(this["NNDPassword"]));
            }
            set {
                this["NNDPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NNDPort {
            get {
                return ((string)(this["NNDPort"]));
            }
            set {
                this["NNDPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NNDSID {
            get {
                return ((string)(this["NNDSID"]));
            }
            set {
                this["NNDSID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NNDNetworkAlias {
            get {
                return ((string)(this["NNDNetworkAlias"]));
            }
            set {
                this["NNDNetworkAlias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NNDIntegratedSec {
            get {
                return ((bool)(this["NNDIntegratedSec"]));
            }
            set {
                this["NNDIntegratedSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NNDLastQuery {
            get {
                return ((string)(this["NNDLastQuery"]));
            }
            set {
                this["NNDLastQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TablePrefix {
            get {
                return ((string)(this["TablePrefix"]));
            }
            set {
                this["TablePrefix"] = value;
            }
        }
    }
}
