//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CalculateEvaluateLexer.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AppliedResearchAssociates.CalculateEvaluate {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class CalculateEvaluateLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		IDENTIFIER=1, NUMBER=2, LEFT_PAREN=3, RIGHT_PAREN=4, TIMES=5, DIVIDED_BY=6, 
		PLUS=7, MINUS=8, AND=9, OR=10, EQUAL=11, NOT_EQUAL=12, LESS_THAN=13, LESS_THAN_OR_EQUAL=14, 
		GREATER_THAN_OR_EQUAL=15, GREATER_THAN=16, COMMA=17, LEFT_BRACKET=18, 
		RIGHT_BRACKET=19, WHITESPACE=20, EMPTY_EVALUATION_LITERAL=21, EVALUATION_LITERAL_OPENING_DELIMITER=22, 
		EVALUATION_LITERAL_CONTENT=23, EVALUATION_LITERAL_CLOSING_DELIMITER=24;
	public const int
		EVALUATION_LITERAL_MODE=1;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE", "EVALUATION_LITERAL_MODE"
	};

	public static readonly string[] ruleNames = {
		"IDENTIFIER", "NUMBER", "LEFT_PAREN", "RIGHT_PAREN", "TIMES", "DIVIDED_BY", 
		"PLUS", "MINUS", "AND", "OR", "EQUAL", "NOT_EQUAL", "LESS_THAN", "LESS_THAN_OR_EQUAL", 
		"GREATER_THAN_OR_EQUAL", "GREATER_THAN", "COMMA", "LEFT_BRACKET", "RIGHT_BRACKET", 
		"WHITESPACE", "DIGIT", "NON_DIGIT", "MANTISSA_PART", "DECIMAL_PART", "EXPONENT_PART", 
		"NATURAL_NUMBER", "EMPTY_EVALUATION_LITERAL", "EVALUATION_LITERAL_OPENING_DELIMITER", 
		"EVALUATION_LITERAL_CONTENT", "EVALUATION_LITERAL_CLOSING_DELIMITER"
	};


	public CalculateEvaluateLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public CalculateEvaluateLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, "'('", "')'", "'*'", "'/'", "'+'", "'-'", null, null, 
		"'='", "'<>'", "'<'", "'<='", "'>='", "'>'", "','", "'['", "']'", null, 
		"'||'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "IDENTIFIER", "NUMBER", "LEFT_PAREN", "RIGHT_PAREN", "TIMES", "DIVIDED_BY", 
		"PLUS", "MINUS", "AND", "OR", "EQUAL", "NOT_EQUAL", "LESS_THAN", "LESS_THAN_OR_EQUAL", 
		"GREATER_THAN_OR_EQUAL", "GREATER_THAN", "COMMA", "LEFT_BRACKET", "RIGHT_BRACKET", 
		"WHITESPACE", "EMPTY_EVALUATION_LITERAL", "EVALUATION_LITERAL_OPENING_DELIMITER", 
		"EVALUATION_LITERAL_CONTENT", "EVALUATION_LITERAL_CLOSING_DELIMITER"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "CalculateEvaluateLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static CalculateEvaluateLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1A', '\xAC', '\b', '\x1', '\b', '\x1', '\x4', '\x2', 
		'\t', '\x2', '\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', 
		'\x5', '\t', '\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', 
		'\x4', '\b', '\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', 
		'\x4', '\v', '\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', 
		'\x4', '\xE', '\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', 
		'\x10', '\x4', '\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', 
		'\x13', '\t', '\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', 
		'\x15', '\x4', '\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', 
		'\x18', '\t', '\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', 
		'\x1A', '\x4', '\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', 
		'\x1D', '\t', '\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', 
		'\x1F', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\a', '\x2', '\x44', 
		'\n', '\x2', '\f', '\x2', '\xE', '\x2', 'G', '\v', '\x2', '\x3', '\x3', 
		'\x3', '\x3', '\x5', '\x3', 'K', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', 
		'\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x15', '\x6', '\x15', 'v', '\n', '\x15', '\r', 
		'\x15', '\xE', '\x15', 'w', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', 
		'\x5', '\x18', '\x82', '\n', '\x18', '\x3', '\x18', '\x5', '\x18', '\x85', 
		'\n', '\x18', '\x3', '\x19', '\x3', '\x19', '\x6', '\x19', '\x89', '\n', 
		'\x19', '\r', '\x19', '\xE', '\x19', '\x8A', '\x3', '\x1A', '\x3', '\x1A', 
		'\x5', '\x1A', '\x8F', '\n', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1B', '\x3', '\x1B', '\x3', '\x1B', '\a', '\x1B', '\x96', '\n', '\x1B', 
		'\f', '\x1B', '\xE', '\x1B', '\x99', '\v', '\x1B', '\x5', '\x1B', '\x9B', 
		'\n', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', 
		'\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x6', '\x1E', 
		'\xA5', '\n', '\x1E', '\r', '\x1E', '\xE', '\x1E', '\xA6', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x2', '\x2', ' ', '\x4', 
		'\x3', '\x6', '\x4', '\b', '\x5', '\n', '\x6', '\f', '\a', '\xE', '\b', 
		'\x10', '\t', '\x12', '\n', '\x14', '\v', '\x16', '\f', '\x18', '\r', 
		'\x1A', '\xE', '\x1C', '\xF', '\x1E', '\x10', ' ', '\x11', '\"', '\x12', 
		'$', '\x13', '&', '\x14', '(', '\x15', '*', '\x16', ',', '\x2', '.', '\x2', 
		'\x30', '\x2', '\x32', '\x2', '\x34', '\x2', '\x36', '\x2', '\x38', '\x17', 
		':', '\x18', '<', '\x19', '>', '\x1A', '\x4', '\x2', '\x3', '\xE', '\x4', 
		'\x2', '\x43', '\x43', '\x63', '\x63', '\x4', '\x2', 'P', 'P', 'p', 'p', 
		'\x4', '\x2', '\x46', '\x46', '\x66', '\x66', '\x4', '\x2', 'Q', 'Q', 
		'q', 'q', '\x4', '\x2', 'T', 'T', 't', 't', '\x5', '\x2', '\v', '\f', 
		'\xF', '\xF', '\"', '\"', '\x3', '\x2', '\x32', ';', '\x5', '\x2', '\x43', 
		'\\', '\x61', '\x61', '\x63', '|', '\x4', '\x2', 'G', 'G', 'g', 'g', '\x4', 
		'\x2', '-', '-', '/', '/', '\x3', '\x2', '\x33', ';', '\x3', '\x2', '~', 
		'~', '\x2', '\xAF', '\x2', '\x4', '\x3', '\x2', '\x2', '\x2', '\x2', '\x6', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\b', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\n', '\x3', '\x2', '\x2', '\x2', '\x2', '\f', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\xE', '\x3', '\x2', '\x2', '\x2', '\x2', '\x10', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x12', '\x3', '\x2', '\x2', '\x2', '\x2', '\x14', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x18', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1A', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1E', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ' ', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\"', '\x3', '\x2', '\x2', '\x2', '\x2', '$', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '&', '\x3', '\x2', '\x2', '\x2', '\x2', '(', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '*', '\x3', '\x2', '\x2', '\x2', '\x2', '\x38', '\x3', '\x2', 
		'\x2', '\x2', '\x2', ':', '\x3', '\x2', '\x2', '\x2', '\x3', '<', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '>', '\x3', '\x2', '\x2', '\x2', '\x4', '@', 
		'\x3', '\x2', '\x2', '\x2', '\x6', 'H', '\x3', '\x2', '\x2', '\x2', '\b', 
		'L', '\x3', '\x2', '\x2', '\x2', '\n', 'N', '\x3', '\x2', '\x2', '\x2', 
		'\f', 'P', '\x3', '\x2', '\x2', '\x2', '\xE', 'R', '\x3', '\x2', '\x2', 
		'\x2', '\x10', 'T', '\x3', '\x2', '\x2', '\x2', '\x12', 'V', '\x3', '\x2', 
		'\x2', '\x2', '\x14', 'X', '\x3', '\x2', '\x2', '\x2', '\x16', '\\', '\x3', 
		'\x2', '\x2', '\x2', '\x18', '_', '\x3', '\x2', '\x2', '\x2', '\x1A', 
		'\x61', '\x3', '\x2', '\x2', '\x2', '\x1C', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '\x1E', '\x66', '\x3', '\x2', '\x2', '\x2', ' ', 'i', '\x3', '\x2', 
		'\x2', '\x2', '\"', 'l', '\x3', '\x2', '\x2', '\x2', '$', 'n', '\x3', 
		'\x2', '\x2', '\x2', '&', 'p', '\x3', '\x2', '\x2', '\x2', '(', 'r', '\x3', 
		'\x2', '\x2', '\x2', '*', 'u', '\x3', '\x2', '\x2', '\x2', ',', '{', '\x3', 
		'\x2', '\x2', '\x2', '.', '}', '\x3', '\x2', '\x2', '\x2', '\x30', '\x84', 
		'\x3', '\x2', '\x2', '\x2', '\x32', '\x86', '\x3', '\x2', '\x2', '\x2', 
		'\x34', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x36', '\x9A', '\x3', '\x2', 
		'\x2', '\x2', '\x38', '\x9C', '\x3', '\x2', '\x2', '\x2', ':', '\x9F', 
		'\x3', '\x2', '\x2', '\x2', '<', '\xA4', '\x3', '\x2', '\x2', '\x2', '>', 
		'\xA8', '\x3', '\x2', '\x2', '\x2', '@', '\x45', '\x5', '.', '\x17', '\x2', 
		'\x41', '\x44', '\x5', '.', '\x17', '\x2', '\x42', '\x44', '\x5', ',', 
		'\x16', '\x2', '\x43', '\x41', '\x3', '\x2', '\x2', '\x2', '\x43', '\x42', 
		'\x3', '\x2', '\x2', '\x2', '\x44', 'G', '\x3', '\x2', '\x2', '\x2', '\x45', 
		'\x43', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\x3', '\x2', '\x2', 
		'\x2', '\x46', '\x5', '\x3', '\x2', '\x2', '\x2', 'G', '\x45', '\x3', 
		'\x2', '\x2', '\x2', 'H', 'J', '\x5', '\x30', '\x18', '\x2', 'I', 'K', 
		'\x5', '\x34', '\x1A', '\x2', 'J', 'I', '\x3', '\x2', '\x2', '\x2', 'J', 
		'K', '\x3', '\x2', '\x2', '\x2', 'K', '\a', '\x3', '\x2', '\x2', '\x2', 
		'L', 'M', '\a', '*', '\x2', '\x2', 'M', '\t', '\x3', '\x2', '\x2', '\x2', 
		'N', 'O', '\a', '+', '\x2', '\x2', 'O', '\v', '\x3', '\x2', '\x2', '\x2', 
		'P', 'Q', '\a', ',', '\x2', '\x2', 'Q', '\r', '\x3', '\x2', '\x2', '\x2', 
		'R', 'S', '\a', '\x31', '\x2', '\x2', 'S', '\xF', '\x3', '\x2', '\x2', 
		'\x2', 'T', 'U', '\a', '-', '\x2', '\x2', 'U', '\x11', '\x3', '\x2', '\x2', 
		'\x2', 'V', 'W', '\a', '/', '\x2', '\x2', 'W', '\x13', '\x3', '\x2', '\x2', 
		'\x2', 'X', 'Y', '\t', '\x2', '\x2', '\x2', 'Y', 'Z', '\t', '\x3', '\x2', 
		'\x2', 'Z', '[', '\t', '\x4', '\x2', '\x2', '[', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\\', ']', '\t', '\x5', '\x2', '\x2', ']', '^', '\t', '\x6', 
		'\x2', '\x2', '^', '\x17', '\x3', '\x2', '\x2', '\x2', '_', '`', '\a', 
		'?', '\x2', '\x2', '`', '\x19', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', 
		'\a', '>', '\x2', '\x2', '\x62', '\x63', '\a', '@', '\x2', '\x2', '\x63', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\a', '>', '\x2', 
		'\x2', '\x65', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x66', 'g', '\a', 
		'>', '\x2', '\x2', 'g', 'h', '\a', '?', '\x2', '\x2', 'h', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', 'i', 'j', '\a', '@', '\x2', '\x2', 'j', 'k', '\a', 
		'?', '\x2', '\x2', 'k', '!', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\a', 
		'@', '\x2', '\x2', 'm', '#', '\x3', '\x2', '\x2', '\x2', 'n', 'o', '\a', 
		'.', '\x2', '\x2', 'o', '%', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', 
		']', '\x2', '\x2', 'q', '\'', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\a', 
		'_', '\x2', '\x2', 's', ')', '\x3', '\x2', '\x2', '\x2', 't', 'v', '\t', 
		'\a', '\x2', '\x2', 'u', 't', '\x3', '\x2', '\x2', '\x2', 'v', 'w', '\x3', 
		'\x2', '\x2', '\x2', 'w', 'u', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\x3', 
		'\x2', '\x2', '\x2', 'x', 'y', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\b', 
		'\x15', '\x2', '\x2', 'z', '+', '\x3', '\x2', '\x2', '\x2', '{', '|', 
		'\t', '\b', '\x2', '\x2', '|', '-', '\x3', '\x2', '\x2', '\x2', '}', '~', 
		'\t', '\t', '\x2', '\x2', '~', '/', '\x3', '\x2', '\x2', '\x2', '\x7F', 
		'\x81', '\x5', '\x36', '\x1B', '\x2', '\x80', '\x82', '\x5', '\x32', '\x19', 
		'\x2', '\x81', '\x80', '\x3', '\x2', '\x2', '\x2', '\x81', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '\x82', '\x85', '\x3', '\x2', '\x2', '\x2', '\x83', 
		'\x85', '\x5', '\x32', '\x19', '\x2', '\x84', '\x7F', '\x3', '\x2', '\x2', 
		'\x2', '\x84', '\x83', '\x3', '\x2', '\x2', '\x2', '\x85', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '\x86', '\x88', '\a', '\x30', '\x2', '\x2', '\x87', 
		'\x89', '\x5', ',', '\x16', '\x2', '\x88', '\x87', '\x3', '\x2', '\x2', 
		'\x2', '\x89', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x88', '\x3', 
		'\x2', '\x2', '\x2', '\x8A', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8B', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8E', '\t', '\n', '\x2', 
		'\x2', '\x8D', '\x8F', '\t', '\v', '\x2', '\x2', '\x8E', '\x8D', '\x3', 
		'\x2', '\x2', '\x2', '\x8E', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x8F', 
		'\x90', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\x5', '\x36', '\x1B', 
		'\x2', '\x91', '\x35', '\x3', '\x2', '\x2', '\x2', '\x92', '\x9B', '\a', 
		'\x32', '\x2', '\x2', '\x93', '\x97', '\t', '\f', '\x2', '\x2', '\x94', 
		'\x96', '\x5', ',', '\x16', '\x2', '\x95', '\x94', '\x3', '\x2', '\x2', 
		'\x2', '\x96', '\x99', '\x3', '\x2', '\x2', '\x2', '\x97', '\x95', '\x3', 
		'\x2', '\x2', '\x2', '\x97', '\x98', '\x3', '\x2', '\x2', '\x2', '\x98', 
		'\x9B', '\x3', '\x2', '\x2', '\x2', '\x99', '\x97', '\x3', '\x2', '\x2', 
		'\x2', '\x9A', '\x92', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x93', '\x3', 
		'\x2', '\x2', '\x2', '\x9B', '\x37', '\x3', '\x2', '\x2', '\x2', '\x9C', 
		'\x9D', '\a', '~', '\x2', '\x2', '\x9D', '\x9E', '\a', '~', '\x2', '\x2', 
		'\x9E', '\x39', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\a', '~', 
		'\x2', '\x2', '\xA0', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA2', 
		'\b', '\x1D', '\x3', '\x2', '\xA2', ';', '\x3', '\x2', '\x2', '\x2', '\xA3', 
		'\xA5', '\n', '\r', '\x2', '\x2', '\xA4', '\xA3', '\x3', '\x2', '\x2', 
		'\x2', '\xA5', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA4', '\x3', 
		'\x2', '\x2', '\x2', '\xA6', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA7', 
		'=', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\a', '~', '\x2', '\x2', 
		'\xA9', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', '\b', '\x1F', 
		'\x4', '\x2', '\xAB', '?', '\x3', '\x2', '\x2', '\x2', '\xF', '\x2', '\x3', 
		'\x43', '\x45', 'J', 'w', '\x81', '\x84', '\x8A', '\x8E', '\x97', '\x9A', 
		'\xA6', '\x5', '\x2', '\x3', '\x2', '\x4', '\x3', '\x2', '\x4', '\x2', 
		'\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace AppliedResearchAssociates.CalculateEvaluate
