//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3053.
// 
#pragma warning disable 1591

namespace RoadCareSecurityOperations.AuthenticateCS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuthenticateCSSoap", Namespace="http://tempuri.org/")]
    public partial class AuthenticateCS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginIntranetCSOperationCompleted;
        
        private System.Threading.SendOrPostCallback encOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AuthenticateCS() {
            this.Url = global::RoadCareSecurityOperations.Properties.Settings.Default.RoadCareSecurityOperations_AuthenticateCS_AuthenticateCS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginIntranetCSCompletedEventHandler LoginIntranetCSCompleted;
        
        /// <remarks/>
        public event encCompletedEventHandler encCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LoginIntranetCS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsLoginResultCS LoginIntranetCS(string userName, int applId) {
            object[] results = this.Invoke("LoginIntranetCS", new object[] {
                        userName,
                        applId});
            return ((clsLoginResultCS)(results[0]));
        }
        
        /// <remarks/>
        public void LoginIntranetCSAsync(string userName, int applId) {
            this.LoginIntranetCSAsync(userName, applId, null);
        }
        
        /// <remarks/>
        public void LoginIntranetCSAsync(string userName, int applId, object userState) {
            if ((this.LoginIntranetCSOperationCompleted == null)) {
                this.LoginIntranetCSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginIntranetCSOperationCompleted);
            }
            this.InvokeAsync("LoginIntranetCS", new object[] {
                        userName,
                        applId}, this.LoginIntranetCSOperationCompleted, userState);
        }
        
        private void OnLoginIntranetCSOperationCompleted(object arg) {
            if ((this.LoginIntranetCSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginIntranetCSCompleted(this, new LoginIntranetCSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/enc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void enc(string str, string pwd) {
            this.Invoke("enc", new object[] {
                        str,
                        pwd});
        }
        
        /// <remarks/>
        public void encAsync(string str, string pwd) {
            this.encAsync(str, pwd, null);
        }
        
        /// <remarks/>
        public void encAsync(string str, string pwd, object userState) {
            if ((this.encOperationCompleted == null)) {
                this.encOperationCompleted = new System.Threading.SendOrPostCallback(this.OnencOperationCompleted);
            }
            this.InvokeAsync("enc", new object[] {
                        str,
                        pwd}, this.encOperationCompleted, userState);
        }
        
        private void OnencOperationCompleted(object arg) {
            if ((this.encCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.encCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsLoginResultCS {
        
        private int resultField;
        
        private string roleField;
        
        private int userIDField;
        
        private string fullNameField;
        
        private string accessRoleField;
        
        private int accessLevelField;
        
        private string userNTLoginField;
        
        private string dbConnectStringField;
        
        private string errMessageField;
        
        /// <remarks/>
        public int result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        public int userID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string accessRole {
            get {
                return this.accessRoleField;
            }
            set {
                this.accessRoleField = value;
            }
        }
        
        /// <remarks/>
        public int accessLevel {
            get {
                return this.accessLevelField;
            }
            set {
                this.accessLevelField = value;
            }
        }
        
        /// <remarks/>
        public string userNTLogin {
            get {
                return this.userNTLoginField;
            }
            set {
                this.userNTLoginField = value;
            }
        }
        
        /// <remarks/>
        public string dbConnectString {
            get {
                return this.dbConnectStringField;
            }
            set {
                this.dbConnectStringField = value;
            }
        }
        
        /// <remarks/>
        public string errMessage {
            get {
                return this.errMessageField;
            }
            set {
                this.errMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void LoginIntranetCSCompletedEventHandler(object sender, LoginIntranetCSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginIntranetCSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginIntranetCSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsLoginResultCS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsLoginResultCS)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void encCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591