USE [DbBackup] /*CHANGE TO TARGET DATABASE*/
GO

/*DELETE DUPLICATE BUDGET_CRITERIA ROWS*/
WITH CTE AS (
	SELECT
		[BUDGET_NAME],
		[CRITERIA],
		ROW_NUMBER() OVER (
			PARTITION BY
				[BUDGET_NAME],
				[CRITERIA]
			ORDER BY
				[BUDGET_NAME],
				[CRITERIA]
		) ROW_NUM
	FROM
		[dbo].[BUDGET_CRITERIA]
)
DELETE FROM CTE
WHERE ROW_NUM > 1;
GO

/*ADD BUDGET_CRITERIA_ID COLUMN TO YEARLYINVESTMENT*/
ALTER TABLE [dbo].[YEARLYINVESTMENT]
ADD [BUDGET_CRITERIA_ID] INT
GO

/*UPDATE YEARLYINVESTMENT ROWS WITH THE BUDGET_CRITERIA_ID FROM BUDGET_CRITERIA WHERE SIMULATION ID & BUDGET NAME MATCH*/
UPDATE [dbo].[YEARLYINVESTMENT] SET [BUDGET_CRITERIA_ID] = bc.BUDGET_CRITERIA_ID
FROM [dbo].[BUDGET_CRITERIA] bc
WHERE [dbo].[YEARLYINVESTMENT].[SIMULATIONID] = bc.SIMULATIONID AND [dbo].[YEARLYINVESTMENT].[BUDGETNAME] = bc.BUDGET_NAME
GO
/*INSERT MISSING BUDGET_CRITERIA ROWS WHERE A MATCH WAS NOT FOUND FROM THE PREVIOUS QUERY*/
INSERT INTO [dbo].[BUDGET_CRITERIA] ([SIMULATIONID], [BUDGET_NAME])
	SELECT [SIMULATIONID], [BUDGETNAME]
	FROM [dbo].[YEARLYINVESTMENT]
	WHERE [BUDGET_CRITERIA_ID] = 0
GO
/*UPDATE THE YEARLYINVESTMENT ROWS AGAIN WITH THE BUDGET_CRITERIA_IDS FOR NEWLY CREATED BUDGET_CRITERIA ROWS*/
UPDATE [dbo].[YEARLYINVESTMENT] SET [BUDGET_CRITERIA_ID] = bc.BUDGET_CRITERIA_ID
FROM [dbo].[BUDGET_CRITERIA] bc
WHERE [dbo].[YEARLYINVESTMENT].[SIMULATIONID] = bc.SIMULATIONID AND [dbo].[YEARLYINVESTMENT].[BUDGETNAME] = bc.BUDGET_NAME AND [dbo].[YEARLYINVESTMENT].[BUDGET_CRITERIA_ID] = 0
GO

/*DROP THE BUDGET_NAME COLUMN FROM YEARLYINVESTMENT*/
ALTER TABLE [dbo].[YEARLYINVESTMENT]
DROP COLUMN [BUDGETNAME]
GO

/*ADD NOT NULL CONSTRAINT TO BUDGET_CRITERIA_ID*/
ALTER TABLE [dbo].[YEARLYINVESTMENT]
ALTER COLUMN [BUDGET_CRITERIA_ID] INT NOT NULL
GO

/*ADD FOREING KEY CONSTRAINT TO BUDGET_CRITERIA_ID ON YEARLYINVESTMENT*/
ALTER TABLE [dbo].[YEARLYINVESTMENT]  WITH CHECK ADD  CONSTRAINT [FK_YEARLYINVESTMENT__BUDGET_CRITERIA] FOREIGN KEY([BUDGET_CRITERIA_ID])
REFERENCES [dbo].[BUDGET_CRITERIA] ([BUDGET_CRITERIA_ID])
GO

ALTER TABLE [dbo].[YEARLYINVESTMENT] CHECK CONSTRAINT [FK_YEARLYINVESTMENT__BUDGET_CRITERIA]
GO
