USE [BridgeCare_Dev] /* Change this to the name of the production database */
GO

/* Change unused CREATOR_ID and USERNAME columns of SIMULATIONS to CREATOR and OWNER */

ALTER TABLE [dbo].[SIMULATIONS]
DROP COLUMN [CREATOR_ID]
GO

EXEC sp_rename 'dbo.SIMULATIONS.USERNAME', 'CREATOR', 'COLUMN'
GO

ALTER TABLE [dbo].[SIMULATIONS]
ADD [OWNER] varchar(200)
GO

/* Create SIMULATION_USERS table */

CREATE TABLE [dbo].[SIMULATION_USERS](
	[ID_] [int] IDENTITY(1,1) NOT NULL,
	[SIMULATIONID] [int] NOT NULL,
	[USERNAME] [varchar](200) NULL,
	[CAN_MODIFY] [bit] NOT NULL,
 CONSTRAINT [PK_SIMULATION_USERS] PRIMARY KEY CLUSTERED 
(
	[ID_] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SIMULATION_USERS]  WITH NOCHECK ADD  CONSTRAINT [FK_SIMULATION_USERS_SIMULATIONS] FOREIGN KEY([SIMULATIONID])
REFERENCES [dbo].[SIMULATIONS] ([SIMULATIONID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[SIMULATION_USERS] CHECK CONSTRAINT [FK_SIMULATION_USERS_SIMULATIONS]
GO