USE [BridgeCare_Dev] /* Change this to the name of the production database */
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

/* Create USER_CRITERIA table */

CREATE TABLE [dbo].[USER_CRITERIA](
	[USERNAME] [varchar](200) NOT NULL,
	[CRITERIA] [varchar](max) NULL,
	[HAS_ACCESS] [bit] NOT NULL,
 CONSTRAINT [PK_USER_CRITERIA] PRIMARY KEY CLUSTERED 
(
	[USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO