//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSET
    {
        public string ASSET1 { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public string CREATOR_NAME { get; set; }
        public string CREATOR_ID { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED { get; set; }
        public string SERVER { get; set; }
        public string DATASOURCE { get; set; }
        public string USERID { get; set; }
        public string SQLVIEW { get; set; }
        public string PASSWORD_ { get; set; }
        public string PROVIDER { get; set; }
        public Nullable<bool> NATIVE_ { get; set; }
    }
}
