//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSETS_CALCULATED
    {
        public int ID_ { get; set; }
        public string ASSET { get; set; }
        public string CALCULATED_PROPERTY { get; set; }
        public string EQUATION { get; set; }
        public byte[] BINARY_EQUATION { get; set; }
        public string CRITERIA { get; set; }
        public byte[] BINARY_CRITERIA { get; set; }
        public string RETURN_TYPE { get; set; }
    }
}
