//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTRIBUTES_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATTRIBUTES_()
        {
            this.ATTRIBUTES_CALCULATED = new HashSet<ATTRIBUTES_CALCULATED>();
            this.COMMIT_CONSEQUENCES = new HashSet<COMMIT_CONSEQUENCES>();
            this.CONSEQUENCES = new HashSet<CONSEQUENCE>();
            this.PERFORMANCEs = new HashSet<PERFORMANCE>();
            this.ROLLUP_CONTROL = new HashSet<ROLLUP_CONTROL>();
            this.TARGET_DEFICIENT = new HashSet<TARGET_DEFICIENT>();
            this.TARGETS = new HashSet<TARGET>();
            this.TREATMENT_CONSEQUENCES = new HashSet<TREATMENT_CONSEQUENCES>();
        }
    
        public string ATTRIBUTE_ { get; set; }
        public Nullable<bool> NATIVE_ { get; set; }
        public string PROVIDER { get; set; }
        public string SERVER { get; set; }
        public string DATASOURCE { get; set; }
        public string USERID { get; set; }
        public string PASSWORD_ { get; set; }
        public string SQLVIEW { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public Nullable<double> LEVEL1 { get; set; }
        public Nullable<double> LEVEL2 { get; set; }
        public Nullable<double> LEVEL3 { get; set; }
        public Nullable<double> LEVEL4 { get; set; }
        public Nullable<double> LEVEL5 { get; set; }
        public Nullable<bool> ASCENDING { get; set; }
        public string TYPE_ { get; set; }
        public string FORMAT { get; set; }
        public string GROUPING { get; set; }
        public Nullable<double> MAXIMUM { get; set; }
        public Nullable<double> MINIMUM_ { get; set; }
        public Nullable<bool> CALCULATED { get; set; }
        public string ASSET { get; set; }
        public string ASSET_PROPERTY { get; set; }
        public string SID { get; set; }
        public string SERVICE_NAME { get; set; }
        public Nullable<bool> INTEGRATED_SECURITY { get; set; }
        public Nullable<int> PORT { get; set; }
        public string SID_ { get; set; }
        public string NETWORK_DEFINITION_NAME { get; set; }
    
        public virtual NETWORK_DEFINITIONS NETWORK_DEFINITIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTRIBUTES_CALCULATED> ATTRIBUTES_CALCULATED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMIT_CONSEQUENCES> COMMIT_CONSEQUENCES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSEQUENCE> CONSEQUENCES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERFORMANCE> PERFORMANCEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLLUP_CONTROL> ROLLUP_CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARGET_DEFICIENT> TARGET_DEFICIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARGET> TARGETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TREATMENT_CONSEQUENCES> TREATMENT_CONSEQUENCES { get; set; }
    }
}
