//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENEFITCOST_13_9
    {
        public int ID_ { get; set; }
        public int SECTIONID { get; set; }
        public int YEARS { get; set; }
        public string TREATMENT { get; set; }
        public Nullable<int> YEARSANY { get; set; }
        public Nullable<int> YEARSSAME { get; set; }
        public string BUDGET { get; set; }
        public Nullable<double> COST_ { get; set; }
        public Nullable<double> REMAINING_LIFE { get; set; }
        public Nullable<double> BENEFIT { get; set; }
        public Nullable<double> BC_RATIO { get; set; }
        public Nullable<int> CONSEQUENCEID { get; set; }
        public Nullable<int> DEFICIENT { get; set; }
        public string RLHASH { get; set; }
        public string CHANGEHASH { get; set; }
        public Nullable<bool> OMS_IGNORE { get; set; }
    }
}
