//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BridgeCareEntities : DbContext
    {
        public BridgeCareEntities()
            : base("name=BridgeCareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AGE> AGEs { get; set; }
        public virtual DbSet<ASSET> ASSETS { get; set; }
        public virtual DbSet<ATTRIBUTES_> ATTRIBUTES_ { get; set; }
        public virtual DbSet<ATTRIBUTES_CALCULATED> ATTRIBUTES_CALCULATED { get; set; }
        public virtual DbSet<CALCULATEFIELD> CALCULATEFIELDs { get; set; }
        public virtual DbSet<COLUMNHEADER> COLUMNHEADERS { get; set; }
        public virtual DbSet<COMMIT_CONSEQUENCES> COMMIT_CONSEQUENCES { get; set; }
        public virtual DbSet<COMMITTED_> COMMITTED_ { get; set; }
        public virtual DbSet<CONNECTION_PARAMETERS> CONNECTION_PARAMETERS { get; set; }
        public virtual DbSet<CONSEQUENCE> CONSEQUENCES { get; set; }
        public virtual DbSet<CONSTRUCTION_HISTORY> CONSTRUCTION_HISTORY { get; set; }
        public virtual DbSet<COST> COSTS { get; set; }
        public virtual DbSet<CR> CRS { get; set; }
        public virtual DbSet<CRS_COEFFICIENT> CRS_COEFFICIENT { get; set; }
        public virtual DbSet<DYNAMIC_SEGMENTATION> DYNAMIC_SEGMENTATION { get; set; }
        public virtual DbSet<FEASIBILITY> FEASIBILITies { get; set; }
        public virtual DbSet<FUNCTIONAL_CLASSFICATION> FUNCTIONAL_CLASSFICATION { get; set; }
        public virtual DbSet<GROUPHEADER> GROUPHEADERS { get; set; }
        public virtual DbSet<INVESTMENT> INVESTMENTS { get; set; }
        public virtual DbSet<IRI> IRIs { get; set; }
        public virtual DbSet<MATERIAL> MATERIALS { get; set; }
        public virtual DbSet<MULTILINE_GEOMETRIES> MULTILINE_GEOMETRIES { get; set; }
        public virtual DbSet<MULTILINE_GEOMETRIES_DEF> MULTILINE_GEOMETRIES_DEF { get; set; }
        public virtual DbSet<MULTILINE_GEOMETRIES_JOIN> MULTILINE_GEOMETRIES_JOIN { get; set; }
        public virtual DbSet<MULTIUSER_LOCK> MULTIUSER_LOCK { get; set; }
        public virtual DbSet<NETWORK_DEFINITION> NETWORK_DEFINITION { get; set; }
        public virtual DbSet<NETWORK_DEFINITIONS> NETWORK_DEFINITIONS { get; set; }
        public virtual DbSet<NETWORK> NETWORKS { get; set; }
        public virtual DbSet<PAGEHEADER> PAGEHEADERS { get; set; }
        public virtual DbSet<PCI_DISTRESS> PCI_DISTRESS { get; set; }
        public virtual DbSet<PERFORMANCE> PERFORMANCEs { get; set; }
        public virtual DbSet<PRIORITIZEDNEED> PRIORITIZEDNEEDs { get; set; }
        public virtual DbSet<PRIORITY> PRIORITies { get; set; }
        public virtual DbSet<PRIORITYFUND> PRIORITYFUNDs { get; set; }
        public virtual DbSet<REPORT> REPORTS { get; set; }
        public virtual DbSet<ROADNAME> ROADNAMEs { get; set; }
        public virtual DbSet<ROWDATA> ROWDATAs { get; set; }
        public virtual DbSet<SCHEDULED> SCHEDULEDs { get; set; }
        public virtual DbSet<SEC_ACTIONGROUPS> SEC_ACTIONGROUPS { get; set; }
        public virtual DbSet<SEC_ACTIONS> SEC_ACTIONS { get; set; }
        public virtual DbSet<SEC_USER_ACTION_PER> SEC_USER_ACTION_PER { get; set; }
        public virtual DbSet<SEC_USER_ACTIONGROUP_PER> SEC_USER_ACTIONGROUP_PER { get; set; }
        public virtual DbSet<SEC_USERGROUP_ACTION_PER> SEC_USERGROUP_ACTION_PER { get; set; }
        public virtual DbSet<SEC_USERGROUP_ACTIONGROUP_PER> SEC_USERGROUP_ACTIONGROUP_PER { get; set; }
        public virtual DbSet<SEC_USERGROUPS> SEC_USERGROUPS { get; set; }
        public virtual DbSet<SEC_USERS> SEC_USERS { get; set; }
        public virtual DbSet<SIMULATION> SIMULATIONS { get; set; }
        public virtual DbSet<TARGET_DEFICIENT> TARGET_DEFICIENT { get; set; }
        public virtual DbSet<TARGET> TARGETS { get; set; }
        public virtual DbSet<TREATMENT_CONSEQUENCES> TREATMENT_CONSEQUENCES { get; set; }
        public virtual DbSet<TREATMENT> TREATMENTS { get; set; }
        public virtual DbSet<X> XS { get; set; }
        public virtual DbSet<YEARLYINVESTMENT> YEARLYINVESTMENTs { get; set; }
        public virtual DbSet<ASSETS_CALCULATED> ASSETS_CALCULATED { get; set; }
        public virtual DbSet<BENEFITCOST_13_9> BENEFITCOST_13_9 { get; set; }
        public virtual DbSet<CONDITIONAL_RSL> CONDITIONAL_RSL { get; set; }
        public virtual DbSet<CRITERIA_SEGMENT> CRITERIA_SEGMENT { get; set; }
        public virtual DbSet<CRS_HIST> CRS_HIST { get; set; }
        public virtual DbSet<DEFICIENT> DEFICIENTS { get; set; }
        public virtual DbSet<DYNAMIC_SEGMENTATION_RESULT> DYNAMIC_SEGMENTATION_RESULT { get; set; }
        public virtual DbSet<NETWORK_TREE> NETWORK_TREE { get; set; }
        public virtual DbSet<PCI> PCIs { get; set; }
        public virtual DbSet<PCI_DETAIL> PCI_DETAIL { get; set; }
        public virtual DbSet<PCI_VALIDATION> PCI_VALIDATION { get; set; }
        public virtual DbSet<PCI_VALIDATION_LINEAR> PCI_VALIDATION_LINEAR { get; set; }
        public virtual DbSet<PENNDOT_DURATION> PENNDOT_DURATION { get; set; }
        public virtual DbSet<REPORT_13_9> REPORT_13_9 { get; set; }
        public virtual DbSet<ROLLUP_CONTROL> ROLLUP_CONTROL { get; set; }
        public virtual DbSet<SECTION_13> SECTION_13 { get; set; }
        public virtual DbSet<SEGMENT_13_NS0> SEGMENT_13_NS0 { get; set; }
        public virtual DbSet<SEGMENT_CONTROL> SEGMENT_CONTROL { get; set; }
        public virtual DbSet<SIMULATION_13_9> SIMULATION_13_9 { get; set; }
        public virtual DbSet<TARGET_13_9> TARGET_13_9 { get; set; }
        public virtual DbSet<BRIDGE_TYPE> BRIDGE_TYPE { get; set; }
        public virtual DbSet<BRIDGE_TYPE_ALT> BRIDGE_TYPE_ALT { get; set; }
        public virtual DbSet<dbo_SEED_DECK_RAW> dbo_SEED_DECK_RAW { get; set; }
        public virtual DbSet<SEED_CULV_RAW> SEED_CULV_RAW { get; set; }
        public virtual DbSet<SEED_DECK_RAW> SEED_DECK_RAW { get; set; }
        public virtual DbSet<SEED_SUB_RAW> SEED_SUB_RAW { get; set; }
        public virtual DbSet<SEED_SUP_RAW> SEED_SUP_RAW { get; set; }
    }
}
