//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRIDGE_TYPE
    {
        public Nullable<int> ID_ { get; set; }
        public Nullable<int> ROUTES { get; set; }
        public Nullable<int> BEGIN_STATION { get; set; }
        public Nullable<int> END_STATION { get; set; }
        public Nullable<int> DIRECTION { get; set; }
        public string FACILITY { get; set; }
        public string SECTION { get; set; }
        public Nullable<int> SAMPLE_ { get; set; }
        public string DATE_ { get; set; }
        public string DATA_ { get; set; }
    }
}
