//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALCULATEFIELD
    {
        public int ID_ { get; set; }
        public string FIELD { get; set; }
        public Nullable<bool> FUTURE { get; set; }
        public string CRITERIA { get; set; }
        public string EQUATION { get; set; }
        public string TYPE_ { get; set; }
        public string FORMAT { get; set; }
        public string GROUPING { get; set; }
    }
}
