//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLUMNHEADER
    {
        public int chID { get; set; }
        public int chReportID { get; set; }
        public string chText { get; set; }
        public int chLineNum { get; set; }
        public string chHAlign { get; set; }
        public Nullable<double> chFontSize { get; set; }
        public Nullable<bool> chFontBold { get; set; }
        public string chFontColor { get; set; }
        public string chInteriorColor { get; set; }
    }
}
