//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDITIONAL_RSL
    {
        public string ATTRIBUTE { get; set; }
        public Nullable<int> BIN { get; set; }
        public double VALUE { get; set; }
        public string CRITERIA { get; set; }
        public Nullable<int> ID { get; set; }
    }
}
