//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONNECTION_PARAMETERS
    {
        public string CONNECTION_NAME { get; set; }
        public int CONNECTION_ID { get; set; }
        public string SERVER { get; set; }
        public string PROVIDER { get; set; }
        public Nullable<bool> NATIVE_ { get; set; }
        public string DATABASE_NAME { get; set; }
        public string SERVICE_NAME { get; set; }
        public string SID { get; set; }
        public string PORT { get; set; }
        public string USERID { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> INTEGRATED_SEC { get; set; }
        public string VIEW_STATEMENT { get; set; }
        public string IDENTIFIER { get; set; }
    }
}
