//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSEQUENCE
    {
        public int CONSEQUENCEID { get; set; }
        public int TREATMENTID { get; set; }
        public string ATTRIBUTE_ { get; set; }
        public string CHANGE_ { get; set; }
        public string CRITERIA { get; set; }
        public byte[] BINARY_CRITERIA { get; set; }
        public string EQUATION { get; set; }
        public Nullable<bool> ISFUNCTION { get; set; }
    
        public virtual ATTRIBUTES_ ATTRIBUTES_ { get; set; }
        public virtual TREATMENT TREATMENT { get; set; }
    }
}
