//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRITERIA_SEGMENT
    {
        public string FAMILY_NAME { get; set; }
        public string FAMILY_EXPRESSION { get; set; }
        public Nullable<int> NETWORKID { get; set; }
    }
}
