//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DYNAMIC_SEGMENTATION
    {
        public int NETWORKID { get; set; }
        public string ROUTES { get; set; }
        public double BEGIN_STATION { get; set; }
        public double END_STATION { get; set; }
        public string DIRECTION { get; set; }
        public string BREAKCAUSE { get; set; }
        public int DYNAMIC_SEGMENTATION_ID { get; set; }
    
        public virtual NETWORK NETWORK { get; set; }
    }
}
