//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPHEADER
    {
        public int ghID { get; set; }
        public int ghReportID { get; set; }
        public string ghText { get; set; }
        public int ghLineNum { get; set; }
        public int ghTextOffset { get; set; }
        public string ghHAlign { get; set; }
        public int ghNumDetailRows { get; set; }
        public Nullable<double> ghFontSize { get; set; }
        public Nullable<bool> ghFontBold { get; set; }
        public string ghFontColor { get; set; }
        public string ghInteriorColor { get; set; }
        public Nullable<bool> ghMergeCells { get; set; }
    }
}
