//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVESTMENT
    {
        public int SIMULATIONID { get; set; }
        public Nullable<int> FIRSTYEAR { get; set; }
        public Nullable<int> NUMBERYEARS { get; set; }
        public Nullable<double> INFLATIONRATE { get; set; }
        public Nullable<double> DISCOUNTRATE { get; set; }
        public string BUDGETORDER { get; set; }
    
        public virtual SIMULATION SIMULATION { get; set; }
    }
}
