//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL
    {
        public string MATERIAL1 { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public string CREATOR_ID { get; set; }
        public string TYPE_ { get; set; }
    }
}
