//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class MULTILINE_GEOMETRIES
    {
        public int MULTILINE_GEOM_ID { get; set; }
        public int FACILITY_ID { get; set; }
        public string LINESTRING { get; set; }
        public Nullable<double> BEGIN_SEGMENT { get; set; }
        public Nullable<double> END_SEGMENT { get; set; }
    
        public virtual NETWORK_DEFINITION NETWORK_DEFINITION { get; set; }
    }
}
