//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NETWORK_DEFINITIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NETWORK_DEFINITIONS()
        {
            this.ATTRIBUTES_ = new HashSet<ATTRIBUTES_>();
            this.NETWORKS = new HashSet<NETWORK>();
        }
    
        public string NETWORK_DEFINITION_NAME { get; set; }
        public int IS_NATIVE { get; set; }
        public string SELECT_STATEMENT { get; set; }
        public string CONNECTION_STRING { get; set; }
        public string TABLE_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTRIBUTES_> ATTRIBUTES_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NETWORK> NETWORKS { get; set; }
    }
}
