//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class NETWORK_DEFINITION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NETWORK_DEFINITION()
        {
            this.MULTILINE_GEOMETRIES = new HashSet<MULTILINE_GEOMETRIES>();
        }
    
        public int ID_ { get; set; }
        public string ROUTES { get; set; }
        public Nullable<double> BEGIN_STATION { get; set; }
        public Nullable<double> END_STATION { get; set; }
        public string DIRECTION { get; set; }
        public string FACILITY { get; set; }
        public string SECTION { get; set; }
        public Nullable<double> AREA { get; set; }
        public string GEOMETRY { get; set; }
        public Nullable<double> Envelope_MinX { get; set; }
        public Nullable<double> Envelope_MinY { get; set; }
        public Nullable<double> Envelope_MaxX { get; set; }
        public Nullable<double> Envelope_MaxY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MULTILINE_GEOMETRIES> MULTILINE_GEOMETRIES { get; set; }
    }
}
