//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCI
    {
        public int ID_ { get; set; }
        public string ROUTES { get; set; }
        public Nullable<double> BEGIN_STATION { get; set; }
        public Nullable<double> END_STATION { get; set; }
        public string DIRECTION { get; set; }
        public string FACILITY { get; set; }
        public string SECTION { get; set; }
        public string SAMPLE_ { get; set; }
        public Nullable<System.DateTime> DATE_ { get; set; }
        public Nullable<bool> IGNORE { get; set; }
        public string METHOD_ { get; set; }
        public Nullable<double> AREA { get; set; }
        public Nullable<double> PCI1 { get; set; }
        public Nullable<double> CLIMATE_PCI { get; set; }
        public Nullable<double> LOAD_PCI { get; set; }
        public Nullable<double> OTHER_PCI { get; set; }
        public string SAMPLE_TYPE { get; set; }
    }
}
