//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCI_DETAIL
    {
        public int ID_ { get; set; }
        public int PCI_ID { get; set; }
        public string DISTRESS { get; set; }
        public string SEVERITY { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<double> EXTENT_ { get; set; }
        public Nullable<double> DEDUCTVALUE { get; set; }
    }
}
