//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCI_VALIDATION
    {
        public int ID { get; set; }
        public string FACILITY { get; set; }
        public string SECTION { get; set; }
        public Nullable<double> SAMPLE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string METHOD { get; set; }
        public string TYPE { get; set; }
        public Nullable<double> AREA { get; set; }
        public string DISTRESS { get; set; }
        public string SEVERITY { get; set; }
        public Nullable<double> AMOUNT { get; set; }
    }
}
