//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PENNDOT_DURATION
    {
        public int BRKEY { get; set; }
        public string DECK { get; set; }
        public string DECK_DURATION { get; set; }
        public string DECK_SD { get; set; }
        public string SUP { get; set; }
        public string SUP_DURATION { get; set; }
        public string SUP_SD { get; set; }
        public string SUB { get; set; }
        public string SUB_DURATION { get; set; }
        public string SUB_SD { get; set; }
        public string CULV { get; set; }
        public string CULV_DURATION { get; set; }
        public string CULV_SD { get; set; }
    }
}
