//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIORITYFUND
    {
        public int PRIORITYFUNDID { get; set; }
        public string BUDGET { get; set; }
        public Nullable<double> FUNDING { get; set; }
        public int PRIORITYID { get; set; }
    
        public virtual PRIORITY PRIORITY { get; set; }
    }
}
