//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIORITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRIORITY()
        {
            this.PRIORITYFUNDs = new HashSet<PRIORITYFUND>();
        }
    
        public int PRIORITYID { get; set; }
        public int SIMULATIONID { get; set; }
        public Nullable<int> PRIORITYLEVEL { get; set; }
        public string CRITERIA { get; set; }
        public byte[] BINARY_CRITERIA { get; set; }
        public Nullable<int> YEARS { get; set; }
    
        public virtual SIMULATION SIMULATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRIORITYFUND> PRIORITYFUNDs { get; set; }
    }
}
