//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORT
    {
        public int reportID { get; set; }
        public string reportName { get; set; }
        public string reportGraphicFile { get; set; }
        public string ghHAlign { get; set; }
        public string ghFontSize { get; set; }
        public Nullable<bool> ghFontBold { get; set; }
        public string ghFontColor { get; set; }
        public string ghInteriorColor { get; set; }
        public Nullable<bool> ghMergeCells { get; set; }
        public string chHAlign { get; set; }
        public string chFontSize { get; set; }
        public Nullable<bool> chFontBold { get; set; }
        public string chFontColor { get; set; }
        public string chInteriorColor { get; set; }
        public Nullable<bool> chMergeCells { get; set; }
        public string ReportType { get; set; }
    }
}
