//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLLUP_CONTROL
    {
        public string ATTRIBUTE_ { get; set; }
        public int NETWORKID { get; set; }
        public string ROLLUPTYPE { get; set; }
    
        public virtual ATTRIBUTES_ ATTRIBUTES_ { get; set; }
        public virtual NETWORK NETWORK { get; set; }
    }
}
