//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROWDATA
    {
        public int rdID { get; set; }
        public int rdReportID { get; set; }
        public Nullable<int> rdGroupID { get; set; }
        public string rdDetailRowLabel { get; set; }
        public int rdFirstDetailColumn { get; set; }
        public string rdFldNameStartsWith { get; set; }
        public Nullable<int> rdLineNum { get; set; }
        public string rdHAlign { get; set; }
        public Nullable<double> rdFontSize { get; set; }
        public Nullable<bool> rdFontBold { get; set; }
        public string rdFontColor { get; set; }
        public string rdInteriorColor { get; set; }
        public Nullable<bool> rdMergeCells { get; set; }
        public Nullable<bool> rdRepeatData { get; set; }
    }
}
