//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_ACTIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEC_ACTIONS()
        {
            this.SEC_USER_ACTION_PER = new HashSet<SEC_USER_ACTION_PER>();
            this.SEC_USERGROUP_ACTION_PER = new HashSet<SEC_USERGROUP_ACTION_PER>();
            this.SEC_ACTIONGROUPS = new HashSet<SEC_ACTIONGROUPS>();
        }
    
        public int ACTION_ID { get; set; }
        public string ACTION_TYPE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> NETWORK_ { get; set; }
        public Nullable<int> SIMULATION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_USER_ACTION_PER> SEC_USER_ACTION_PER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_USERGROUP_ACTION_PER> SEC_USERGROUP_ACTION_PER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_ACTIONGROUPS> SEC_ACTIONGROUPS { get; set; }
    }
}
