//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_ACTIONGROUPS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEC_ACTIONGROUPS()
        {
            this.SEC_USER_ACTIONGROUP_PER = new HashSet<SEC_USER_ACTIONGROUP_PER>();
            this.SEC_USERGROUP_ACTIONGROUP_PER = new HashSet<SEC_USERGROUP_ACTIONGROUP_PER>();
            this.SEC_ACTIONS = new HashSet<SEC_ACTIONS>();
        }
    
        public int ACTIONGROUP_ID { get; set; }
        public string ACTIONGROUP_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_USER_ACTIONGROUP_PER> SEC_USER_ACTIONGROUP_PER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_USERGROUP_ACTIONGROUP_PER> SEC_USERGROUP_ACTIONGROUP_PER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_ACTIONS> SEC_ACTIONS { get; set; }
    }
}
