//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_USER_ACTIONGROUP_PER
    {
        public int USER_ID { get; set; }
        public int ACTIONGROUP_ID { get; set; }
        public string ACCESS_LEVEL { get; set; }
    
        public virtual SEC_ACTIONGROUPS SEC_ACTIONGROUPS { get; set; }
        public virtual SEC_USERS SEC_USERS { get; set; }
    }
}
