//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEC_USERS()
        {
            this.SEC_USER_ACTION_PER = new HashSet<SEC_USER_ACTION_PER>();
            this.SEC_USER_ACTIONGROUP_PER = new HashSet<SEC_USER_ACTIONGROUP_PER>();
            this.SEC_USERGROUPS = new HashSet<SEC_USERGROUPS>();
        }
    
        public int USER_ID { get; set; }
        public string USER_LOGIN { get; set; }
        public string PASSWORD_ { get; set; }
        public string EMAIL { get; set; }
        public string LOWERED_EMAIL { get; set; }
        public string PASSWORD_QUESTION { get; set; }
        public string PASSWORD_ANSWER { get; set; }
        public bool IS_APPROVED { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> LAST_LOGIN_DATE { get; set; }
        public Nullable<System.DateTime> LAST_PASSWORD_CHANGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_USER_ACTION_PER> SEC_USER_ACTION_PER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_USER_ACTIONGROUP_PER> SEC_USER_ACTIONGROUP_PER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_USERGROUPS> SEC_USERGROUPS { get; set; }
    }
}
