//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_USERGROUPS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEC_USERGROUPS()
        {
            this.SEC_USERGROUP_ACTION_PER = new HashSet<SEC_USERGROUP_ACTION_PER>();
            this.SEC_USERGROUP_ACTIONGROUP_PER = new HashSet<SEC_USERGROUP_ACTIONGROUP_PER>();
            this.SEC_USERS = new HashSet<SEC_USERS>();
        }
    
        public int USERGROUP_ID { get; set; }
        public string USERGROUP_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_USERGROUP_ACTION_PER> SEC_USERGROUP_ACTION_PER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_USERGROUP_ACTIONGROUP_PER> SEC_USERGROUP_ACTIONGROUP_PER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEC_USERS> SEC_USERS { get; set; }
    }
}
