//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECTION_13
    {
        public int SECTIONID { get; set; }
        public string FACILITY { get; set; }
        public Nullable<double> BEGIN_STATION { get; set; }
        public Nullable<double> END_STATION { get; set; }
        public string DIRECTION { get; set; }
        public string SECTION { get; set; }
        public Nullable<double> AREA { get; set; }
        public string UNITS { get; set; }
        public string GEOMETRY { get; set; }
        public Nullable<double> ENVELOPE_MINX { get; set; }
        public Nullable<double> ENVELOPE_MAXX { get; set; }
        public Nullable<double> ENVELOPE_MINY { get; set; }
        public Nullable<double> ENVELOPE_MAXY { get; set; }
    }
}
