//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEED_DECK_RAW
    {
        public string BR_KEY { get; set; }
        public string DECK { get; set; }
        public Nullable<int> DURATION { get; set; }
        public Nullable<double> DECK_INDEX { get; set; }
        public Nullable<int> DECK_COUNT { get; set; }
    }
}
