//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGMENT_CONTROL
    {
        public int NETWORKID { get; set; }
        public string SEGMENT_TABLE { get; set; }
        public string ATTRIBUTE_ { get; set; }
        public Nullable<int> PCI_BEGIN_YEAR { get; set; }
        public Nullable<int> PCI_END_YEAR { get; set; }
    
        public virtual NETWORK NETWORK { get; set; }
    }
}
