//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMULATION_13_9
    {
        public int SECTIONID { get; set; }
        public Nullable<double> AGE_2019 { get; set; }
        public string BRIDGE_TYPE_2019 { get; set; }
        public string BRIDGE_TYPE_ALT_2019 { get; set; }
        public string BUS_PLAN_NETWORK_2019 { get; set; }
        public Nullable<double> CONDITIONINDEX_2019 { get; set; }
        public Nullable<double> CULV_SEEDED_2019 { get; set; }
        public Nullable<double> DECK_AREA_2019 { get; set; }
        public Nullable<double> DECK_SEEDED_2019 { get; set; }
        public string FAMILY_ID_2019 { get; set; }
        public string OWNER_CODE_2019 { get; set; }
        public Nullable<double> SD_RISK_SCORE_2019 { get; set; }
        public Nullable<double> SUB_SEEDED_2019 { get; set; }
        public Nullable<double> SUP_SEEDED_2019 { get; set; }
        public Nullable<double> AGE_2020 { get; set; }
        public string BRIDGE_TYPE_2020 { get; set; }
        public string BRIDGE_TYPE_ALT_2020 { get; set; }
        public string BUS_PLAN_NETWORK_2020 { get; set; }
        public Nullable<double> CONDITIONINDEX_2020 { get; set; }
        public Nullable<double> CULV_SEEDED_2020 { get; set; }
        public Nullable<double> DECK_AREA_2020 { get; set; }
        public Nullable<double> DECK_SEEDED_2020 { get; set; }
        public string FAMILY_ID_2020 { get; set; }
        public string OWNER_CODE_2020 { get; set; }
        public Nullable<double> SD_RISK_SCORE_2020 { get; set; }
        public Nullable<double> SUB_SEEDED_2020 { get; set; }
        public Nullable<double> SUP_SEEDED_2020 { get; set; }
        public Nullable<double> AGE_2021 { get; set; }
        public string BRIDGE_TYPE_2021 { get; set; }
        public string BRIDGE_TYPE_ALT_2021 { get; set; }
        public string BUS_PLAN_NETWORK_2021 { get; set; }
        public Nullable<double> CONDITIONINDEX_2021 { get; set; }
        public Nullable<double> CULV_SEEDED_2021 { get; set; }
        public Nullable<double> DECK_AREA_2021 { get; set; }
        public Nullable<double> DECK_SEEDED_2021 { get; set; }
        public string FAMILY_ID_2021 { get; set; }
        public string OWNER_CODE_2021 { get; set; }
        public Nullable<double> SD_RISK_SCORE_2021 { get; set; }
        public Nullable<double> SUB_SEEDED_2021 { get; set; }
        public Nullable<double> SUP_SEEDED_2021 { get; set; }
        public Nullable<double> AGE_2022 { get; set; }
        public string BRIDGE_TYPE_2022 { get; set; }
        public string BRIDGE_TYPE_ALT_2022 { get; set; }
        public string BUS_PLAN_NETWORK_2022 { get; set; }
        public Nullable<double> CONDITIONINDEX_2022 { get; set; }
        public Nullable<double> CULV_SEEDED_2022 { get; set; }
        public Nullable<double> DECK_AREA_2022 { get; set; }
        public Nullable<double> DECK_SEEDED_2022 { get; set; }
        public string FAMILY_ID_2022 { get; set; }
        public string OWNER_CODE_2022 { get; set; }
        public Nullable<double> SD_RISK_SCORE_2022 { get; set; }
        public Nullable<double> SUB_SEEDED_2022 { get; set; }
        public Nullable<double> SUP_SEEDED_2022 { get; set; }
        public Nullable<double> AGE_2023 { get; set; }
        public string BRIDGE_TYPE_2023 { get; set; }
        public string BRIDGE_TYPE_ALT_2023 { get; set; }
        public string BUS_PLAN_NETWORK_2023 { get; set; }
        public Nullable<double> CONDITIONINDEX_2023 { get; set; }
        public Nullable<double> CULV_SEEDED_2023 { get; set; }
        public Nullable<double> DECK_AREA_2023 { get; set; }
        public Nullable<double> DECK_SEEDED_2023 { get; set; }
        public string FAMILY_ID_2023 { get; set; }
        public string OWNER_CODE_2023 { get; set; }
        public Nullable<double> SD_RISK_SCORE_2023 { get; set; }
        public Nullable<double> SUB_SEEDED_2023 { get; set; }
        public Nullable<double> SUP_SEEDED_2023 { get; set; }
        public Nullable<double> AGE_2024 { get; set; }
        public string BRIDGE_TYPE_2024 { get; set; }
        public string BRIDGE_TYPE_ALT_2024 { get; set; }
        public string BUS_PLAN_NETWORK_2024 { get; set; }
        public Nullable<double> CONDITIONINDEX_2024 { get; set; }
        public Nullable<double> CULV_SEEDED_2024 { get; set; }
        public Nullable<double> DECK_AREA_2024 { get; set; }
        public Nullable<double> DECK_SEEDED_2024 { get; set; }
        public string FAMILY_ID_2024 { get; set; }
        public string OWNER_CODE_2024 { get; set; }
        public Nullable<double> SD_RISK_SCORE_2024 { get; set; }
        public Nullable<double> SUB_SEEDED_2024 { get; set; }
        public Nullable<double> SUP_SEEDED_2024 { get; set; }
        public Nullable<double> AGE_2025 { get; set; }
        public string BRIDGE_TYPE_2025 { get; set; }
        public string BRIDGE_TYPE_ALT_2025 { get; set; }
        public string BUS_PLAN_NETWORK_2025 { get; set; }
        public Nullable<double> CONDITIONINDEX_2025 { get; set; }
        public Nullable<double> CULV_SEEDED_2025 { get; set; }
        public Nullable<double> DECK_AREA_2025 { get; set; }
        public Nullable<double> DECK_SEEDED_2025 { get; set; }
        public string FAMILY_ID_2025 { get; set; }
        public string OWNER_CODE_2025 { get; set; }
        public Nullable<double> SD_RISK_SCORE_2025 { get; set; }
        public Nullable<double> SUB_SEEDED_2025 { get; set; }
        public Nullable<double> SUP_SEEDED_2025 { get; set; }
        public Nullable<double> AGE_2026 { get; set; }
        public string BRIDGE_TYPE_2026 { get; set; }
        public string BRIDGE_TYPE_ALT_2026 { get; set; }
        public string BUS_PLAN_NETWORK_2026 { get; set; }
        public Nullable<double> CONDITIONINDEX_2026 { get; set; }
        public Nullable<double> CULV_SEEDED_2026 { get; set; }
        public Nullable<double> DECK_AREA_2026 { get; set; }
        public Nullable<double> DECK_SEEDED_2026 { get; set; }
        public string FAMILY_ID_2026 { get; set; }
        public string OWNER_CODE_2026 { get; set; }
        public Nullable<double> SD_RISK_SCORE_2026 { get; set; }
        public Nullable<double> SUB_SEEDED_2026 { get; set; }
        public Nullable<double> SUP_SEEDED_2026 { get; set; }
        public Nullable<double> AGE_2027 { get; set; }
        public string BRIDGE_TYPE_2027 { get; set; }
        public string BRIDGE_TYPE_ALT_2027 { get; set; }
        public string BUS_PLAN_NETWORK_2027 { get; set; }
        public Nullable<double> CONDITIONINDEX_2027 { get; set; }
        public Nullable<double> CULV_SEEDED_2027 { get; set; }
        public Nullable<double> DECK_AREA_2027 { get; set; }
        public Nullable<double> DECK_SEEDED_2027 { get; set; }
        public string FAMILY_ID_2027 { get; set; }
        public string OWNER_CODE_2027 { get; set; }
        public Nullable<double> SD_RISK_SCORE_2027 { get; set; }
        public Nullable<double> SUB_SEEDED_2027 { get; set; }
        public Nullable<double> SUP_SEEDED_2027 { get; set; }
        public Nullable<double> AGE_2028 { get; set; }
        public string BRIDGE_TYPE_2028 { get; set; }
        public string BRIDGE_TYPE_ALT_2028 { get; set; }
        public string BUS_PLAN_NETWORK_2028 { get; set; }
        public Nullable<double> CONDITIONINDEX_2028 { get; set; }
        public Nullable<double> CULV_SEEDED_2028 { get; set; }
        public Nullable<double> DECK_AREA_2028 { get; set; }
        public Nullable<double> DECK_SEEDED_2028 { get; set; }
        public string FAMILY_ID_2028 { get; set; }
        public string OWNER_CODE_2028 { get; set; }
        public Nullable<double> SD_RISK_SCORE_2028 { get; set; }
        public Nullable<double> SUB_SEEDED_2028 { get; set; }
        public Nullable<double> SUP_SEEDED_2028 { get; set; }
        public Nullable<double> AGE_2029 { get; set; }
        public string BRIDGE_TYPE_2029 { get; set; }
        public string BRIDGE_TYPE_ALT_2029 { get; set; }
        public string BUS_PLAN_NETWORK_2029 { get; set; }
        public Nullable<double> CONDITIONINDEX_2029 { get; set; }
        public Nullable<double> CULV_SEEDED_2029 { get; set; }
        public Nullable<double> DECK_AREA_2029 { get; set; }
        public Nullable<double> DECK_SEEDED_2029 { get; set; }
        public string FAMILY_ID_2029 { get; set; }
        public string OWNER_CODE_2029 { get; set; }
        public Nullable<double> SD_RISK_SCORE_2029 { get; set; }
        public Nullable<double> SUB_SEEDED_2029 { get; set; }
        public Nullable<double> SUP_SEEDED_2029 { get; set; }
        public Nullable<double> AGE_2030 { get; set; }
        public string BRIDGE_TYPE_2030 { get; set; }
        public string BRIDGE_TYPE_ALT_2030 { get; set; }
        public string BUS_PLAN_NETWORK_2030 { get; set; }
        public Nullable<double> CONDITIONINDEX_2030 { get; set; }
        public Nullable<double> CULV_SEEDED_2030 { get; set; }
        public Nullable<double> DECK_AREA_2030 { get; set; }
        public Nullable<double> DECK_SEEDED_2030 { get; set; }
        public string FAMILY_ID_2030 { get; set; }
        public string OWNER_CODE_2030 { get; set; }
        public Nullable<double> SD_RISK_SCORE_2030 { get; set; }
        public Nullable<double> SUB_SEEDED_2030 { get; set; }
        public Nullable<double> SUP_SEEDED_2030 { get; set; }
        public Nullable<double> AGE_0 { get; set; }
        public string BRIDGE_TYPE_0 { get; set; }
        public string BRIDGE_TYPE_ALT_0 { get; set; }
        public string BUS_PLAN_NETWORK_0 { get; set; }
        public Nullable<double> CONDITIONINDEX_0 { get; set; }
        public Nullable<double> CULV_SEEDED_0 { get; set; }
        public Nullable<double> DECK_AREA_0 { get; set; }
        public Nullable<double> DECK_SEEDED_0 { get; set; }
        public string FAMILY_ID_0 { get; set; }
        public string OWNER_CODE_0 { get; set; }
        public Nullable<double> SD_RISK_SCORE_0 { get; set; }
        public Nullable<double> SUB_SEEDED_0 { get; set; }
        public Nullable<double> SUP_SEEDED_0 { get; set; }
    }
}
