//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIMULATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIMULATION()
        {
            this.COMMITTED_ = new HashSet<COMMITTED_>();
            this.PERFORMANCEs = new HashSet<PERFORMANCE>();
            this.PRIORITIZEDNEEDs = new HashSet<PRIORITIZEDNEED>();
            this.PRIORITies = new HashSet<PRIORITY>();
            this.DEFICIENTS = new HashSet<DEFICIENT>();
            this.TARGET_DEFICIENT = new HashSet<TARGET_DEFICIENT>();
            this.TARGETS = new HashSet<TARGET>();
            this.TREATMENTS = new HashSet<TREATMENT>();
            this.YEARLYINVESTMENTs = new HashSet<YEARLYINVESTMENT>();
        }
    
        public int SIMULATIONID { get; set; }
        public Nullable<int> NETWORKID { get; set; }
        public string SIMULATION1 { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public Nullable<System.DateTime> DATE_LAST_RUN { get; set; }
        public string CREATOR_ID { get; set; }
        public string USERNAME { get; set; }
        public Nullable<int> PERMISSIONS { get; set; }
        public string JURISDICTION { get; set; }
        public string ANALYSIS { get; set; }
        public string BUDGET_CONSTRAINT { get; set; }
        public string WEIGHTING { get; set; }
        public string BENEFIT_VARIABLE { get; set; }
        public Nullable<double> BENEFIT_LIMIT { get; set; }
        public Nullable<int> COMMITTED_START { get; set; }
        public Nullable<int> COMMITTED_PERIOD { get; set; }
        public string SIMULATION_VARIABLES { get; set; }
        public string RUN_TIME { get; set; }
        public Nullable<bool> USE_CONDITIONAL_RSL { get; set; }
        public Nullable<bool> USE_CUMULATIVE_COST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMITTED_> COMMITTED_ { get; set; }
        public virtual INVESTMENT INVESTMENT { get; set; }
        public virtual NETWORK NETWORK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERFORMANCE> PERFORMANCEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRIORITIZEDNEED> PRIORITIZEDNEEDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRIORITY> PRIORITies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEFICIENT> DEFICIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARGET_DEFICIENT> TARGET_DEFICIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TARGET> TARGETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TREATMENT> TREATMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEARLYINVESTMENT> YEARLYINVESTMENTs { get; set; }
    }
}
