//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARGET_13_9
    {
        public int ID_ { get; set; }
        public Nullable<int> TARGETID { get; set; }
        public Nullable<int> YEARS { get; set; }
        public Nullable<double> TARGETMET { get; set; }
        public Nullable<double> AREA { get; set; }
        public Nullable<bool> ISDEFICIENT { get; set; }
    }
}
