//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREATMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TREATMENT()
        {
            this.CONSEQUENCES = new HashSet<CONSEQUENCE>();
            this.COSTS = new HashSet<COST>();
            this.FEASIBILITies = new HashSet<FEASIBILITY>();
            this.SCHEDULEDs = new HashSet<SCHEDULED>();
            this.TREATMENT_CONSEQUENCES = new HashSet<TREATMENT_CONSEQUENCES>();
        }
    
        public int TREATMENTID { get; set; }
        public int SIMULATIONID { get; set; }
        public string TREATMENT1 { get; set; }
        public int BEFOREANY { get; set; }
        public int BEFORESAME { get; set; }
        public string BUDGET { get; set; }
        public string DESCRIPTION { get; set; }
        public string OMS_IS_EXCLUSIVE { get; set; }
        public string OMS_IS_REPEAT { get; set; }
        public string OMS_REPEAT_START { get; set; }
        public string OMS_REPEAT_INTERVAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSEQUENCE> CONSEQUENCES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COST> COSTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEASIBILITY> FEASIBILITies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCHEDULED> SCHEDULEDs { get; set; }
        public virtual SIMULATION SIMULATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TREATMENT_CONSEQUENCES> TREATMENT_CONSEQUENCES { get; set; }
    }
}
