//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEARLYINVESTMENT
    {
        public int YEARID { get; set; }
        public int SIMULATIONID { get; set; }
        public int YEAR_ { get; set; }
        public string BUDGETNAME { get; set; }
        public Nullable<double> AMOUNT { get; set; }
    
        public virtual SIMULATION SIMULATION { get; set; }
    }
}
