//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCImageView3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IMAGEVIEW_FILEPATH {
            get {
                return ((string)(this["IMAGEVIEW_FILEPATH"]));
            }
            set {
                this["IMAGEVIEW_FILEPATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point APP_SIZE {
            get {
                return ((global::System.Drawing.Point)(this["APP_SIZE"]));
            }
            set {
                this["APP_SIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WindowGeometry {
            get {
                return ((string)(this["WindowGeometry"]));
            }
            set {
                this["WindowGeometry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("db.ico")]
        public string ATTRIBUTE_IMAGE_KEY {
            get {
                return ((string)(this["ATTRIBUTE_IMAGE_KEY"]));
            }
            set {
                this["ATTRIBUTE_IMAGE_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lighton.ico")]
        public string ATTRIBUTE_IMAGE_KEY_SELECTED {
            get {
                return ((string)(this["ATTRIBUTE_IMAGE_KEY_SELECTED"]));
            }
            set {
                this["ATTRIBUTE_IMAGE_KEY_SELECTED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double FRAMERATE {
            get {
                return ((double)(this["FRAMERATE"]));
            }
            set {
                this["FRAMERATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FRAMESKIP {
            get {
                return ((int)(this["FRAMESKIP"]));
            }
            set {
                this["FRAMESKIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string REFERENCETYPE {
            get {
                return ((string)(this["REFERENCETYPE"]));
            }
            set {
                this["REFERENCETYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FACILITY {
            get {
                return ((string)(this["FACILITY"]));
            }
            set {
                this["FACILITY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IMAGEPATH {
            get {
                return ((string)(this["IMAGEPATH"]));
            }
            set {
                this["IMAGEPATH"] = value;
            }
        }
    }
}
